server:
  port: 8093

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**, /readMyBooks/**
        - id: manuscript
          uri: http://localhost:8083
          predicates:
            - Path=/manuscripts/**, 
        - id: reader
          uri: http://localhost:8084
          predicates:
            - Path=/managerReaders/**, 
        - id: manager
          uri: http://localhost:8085
          predicates:
            - Path=/manageAuthors/**, /manageReaderInfos/**, /requestRegisterMonitorings/**, /readAuthorInfos/**, /readReaderInfos/**
        - id: point
          uri: http://localhost:8086
          predicates:
            - Path=/points/**, 
        - id: purchasebook
          uri: http://localhost:8087
          predicates:
            - Path=/purchasedBooks/**, 
        - id: subscription
          uri: http://localhost:8088
          predicates:
            - Path=/subscribes/**, 
        - id: payment
          uri: http://localhost:8089
          predicates:
            - Path=/payments/**, 
        - id: aiconnect
          uri: http://localhost:8090
          predicates:
            - Path=/bookCovers/**, /bookSummaries/**, 
        - id: book
          uri: http://localhost:8091
          predicates:
            - Path=/books/**, 
        - id: dashboard
          uri: http://localhost:8092
          predicates:
            - Path=, /availiableBookLists/**
        - id: frontend
          uri: http://localhost:3000 
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/authors/**, 
        - id: manuscript
          uri: http://manuscript:8080
          predicates:
            - Path=/manuscripts/**, 
        - id: reader
          uri: http://reader:8080
          predicates:
            - Path=/managerReaders/**, 
        - id: manager
          uri: http://manager:8080
          predicates:
            - Path=/manageAuthors/**, /manageReaderInfos/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: purchasebook
          uri: http://purchasebook:8080
          predicates:
            - Path=/purchasedBooks/**, 
        - id: subscription
          uri: http://subscription:8080
          predicates:
            - Path=/subscribes/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: aiconnect
          uri: http://aiconnect:8080
          predicates:
            - Path=/bookCovers/**, /bookSummaries/**, 
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
